# Generated by Django 3.2.4 on 2021-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_branc_productos_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='sku',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
