# Generated by Django 3.2.4 on 2021-06-24 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_bitacoraconsultausuarioanonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraconsultausuarioanonimo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
